const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),assert=require('node:assert/strict');
const base=process.env.SITE_BASE||'http://127.0.0.1:8768/';
(async()=>{
 const records=JSON.parse(fs.readFileSync('data/reference-readers.json','utf8'));assert.equal(records.length,27);
 const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 for(const width of [390,1440]){await page.setViewportSize({width,height:900});for(const r of records){const response=await page.goto(base+r.slug+'.html#read',{waitUntil:'domcontentloaded'});assert.equal(response.status(),200);assert.equal(await page.locator('h1').count(),1);assert.ok(await page.locator('a[download]').count()>=2);assert.ok(await page.locator('.source-reader').innerText());if(r.previewType==='pages'){assert.equal(await page.locator('.source-page').count(),r.pageCount);await page.locator('.source-page img').first().evaluate(i=>i.decode());assert.equal(await page.locator('.source-page img').count(),r.pageCount);}const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`${width}px ${r.slug} overflow`);}console.log(`PASS: all 27 complete online readers at ${width}px`);}
 await page.goto(base+'references.html#documents');assert.equal(await page.locator('.read-source').count(),27);assert.equal(await page.locator('.reference-actions a[download]').count(),27);await page.locator('#document-search').fill('planning document');assert.equal(await page.locator('.reference-item[data-search]:visible').count(),1);await page.locator('.read-source:visible').click();await page.waitForURL('**/source-planning-document.html#read');const jump=page.locator('details:has(.source-page-jump)');assert.equal(await jump.locator('.source-page-jump').isVisible(),false);await jump.locator('summary').click();assert.equal(await jump.locator('.source-page-jump').isVisible(),true);await jump.locator('a').nth(1).click();await page.waitForURL('**/source-planning-document.html#source-page-2');await page.locator('.source-page-text summary').first().click();assert.ok((await page.locator('.source-extracted-text').first().innerText()).length>30);
 await page.setViewportSize({width:390,height:844});for(const slug of ['source-planning-document','source-document-03','source-document-08']){await page.goto(base+slug+'.html#read',{waitUntil:'networkidle'});await page.screenshot({path:'work/'+slug+'-phone.png'});}assert.deepEqual(errors,[]);await browser.close();console.log('PASS: library read/download choices; search; full-page images; selectable text; no browser errors');
})().catch(e=>{console.error(e);process.exit(1)});
