"""Women-led design questions and a personal brief, without presupposing answers."""
def build_equality(h,network_ready=False):
    section,card,image=h['section'],h['card'],h['image']
    body=section('If equality were being designed now,','<p class="equality-question">What would women want and need from the places, workplaces and systems around them?</p><p>This is a question for women to answer through their own lives. A good design begins with listening, gives people power over the choices, and tests whether daily life actually improves.</p><p>Across cities, outer suburbs, country towns, the outback and island communities, the answer can change. Australia is home to First Nations women, migrants from across the world and families with many generations here. A global network needs that same openness to different places and experiences.</p>','light')
    body+=section('Start with a life.<br>Then examine the system.','<p>Ask about an ordinary day. What takes more time, money or effort than it should? Where does a woman have to adapt herself to a system that could have been designed differently? What already works well, and what should be protected?</p><p>A woman might want reliable transport, a workshop tool that fits her body, time to care for family, more influence at work, a place to feel beautiful, affordable space for an enterprise, or a different future altogether. These are examples to explore, not answers to impose.</p><div class="callout"><h3>Who is shaping the question?</h3><p>Invite the women who would use, maintain, pay for, work in and live beside the proposed system. Make it possible to participate through different languages, schedules, locations and ways of communicating. Pay for substantial design work where it is part of the project.</p></div>')
    lenses=[('Power and ownership','Who sets priorities, controls resources and can change a decision? Explore ownership, executive authority, board influence and the right to challenge a system.'),('Time and care','How do working hours, caring responsibilities, recovery, learning and time for a life fit together? Look at the whole day, including unpaid work.'),('Places and access','What changes between a capital city, outer suburb, regional town, remote property and island? Examine housing, transport, services, connection and physical access.'),('Bodies and everyday design','Whose bodies fit the furniture, clothing, equipment, vehicles and spaces? Involve women of different sizes, heights, bust sizes, ages, mobility and sensory needs.'),('Income and opportunity','Can women afford to take part, learn, build and lead? Ask about pay, enterprise income, training, capital, risk and routes into ownership.'),('Belonging and self-expression','Can women bring their language, culture, faith, style and personality? Glamorous, practical, nerdy, country, urban or something entirely their own: no single look defines a leader.')]
    body+=section('Six ways into the bigger question.','<div class="grid two equality-lens">'+''.join(card(t,p) for t,p in lenses)+'</div>','plum')
    steps=[('Listen with the women involved','Gather actual experiences, including disagreements. Ask what a better day would look like and whose experience is still missing.'),('Choose a change together','Translate a need into a design decision. Record who has authority, who bears the cost and who should benefit.'),('Try a small version','Test a timetable, space, service, tool or decision process with willing participants. Keep the first experiment useful and manageable.'),('Review what changed','Look at time, cost, access, income, safety, influence or another measure chosen by the participants. Share the result and revise the design.')]
    body+=section('Turn the question into a practical test.','<div class="journey">'+''.join(f'<article><span class="number">{i:02d}</span><h3>{t}</h3><p>{p}</p></article>' for i,(t,p) in enumerate(steps,1))+'</div>','light')
    body+=section('Bring the question into the network.','<p>Every enterprise brief includes questions about who it serves and how women could shape its design. The Queens bring different perspectives; the people affected supply the lived knowledge and make the decisions.</p><div class="grid two">'+card('Choose a Queen','Explore the mentor whose perspective could help you investigate a need, compare choices or prepare a decision.','ai-queens.html')+card('Explore an enterprise field','Take a question about life, work or place into one of the original 120 enterprise suggestions.','catalogue.html')+'</div>')
    fields=[('place','The environment or system I would redesign','For example: a workplace, town centre, transport route, caring service, investment process or piece of equipment.'),('voices','Whose experiences should shape it?','Who uses it, who works in it, and whose perspective is easy to miss?'),('needs','What do women say they want or need?','Record actual experiences, priorities and differences. Leave room for answers you did not expect.'),('power','Which decisions should women control?','Name meaningful authority over design, resources, operation or ownership.'),('change','What change could we test first?','Choose a small change and the people who should help design it.'),('evidence','How would we know it made a difference?','Choose measures that matter to the participants.')]
    form='<form id="equality-form" class="plan-form">'+''.join(f'<div class="field"><label for="equality-{k}">{title}</label><textarea id="equality-{k}" name="{k}" rows="4" placeholder="{hint}"></textarea></div>' for k,title,hint in fields)+'</form>'
    body+=section('Make your own design brief.','<p>Begin with an environment or system you know. These notes stay in your browser and can be downloaded. They are not sent to a project team or published.</p>'+form+'<div class="actions"><button type="button" class="button" id="export-equality">Download my design brief ↓</button>'+('<a class="button secondary" href="network.html#my-pathway">Connect it to my pathway →</a>' if network_ready else '<a class="button secondary" href="catalogue.html">Explore the enterprise ideas →</a>')+'</div><p id="equality-status" class="notice" role="status"></p>','plum')
    body+=section('The invitation stays open.','<p>This design focus develops the 500 Queens purpose of substantive leadership, meaningful economic influence and a rewarding life. It treats equality as something women help shape in the systems around them, with space for different priorities and ways of living.</p><a class="text-link" href="references/documents/queens-venture-capital-planning-document.pdf">Read the 500 Queens planning document →</a>','light')
    return body
