"""Record source identities separately from the user's corrected visual direction."""
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
source=(ROOT.parent/'Queens_Venture/index.html').read_text(encoding='utf-8')
roster=source.split('queens: [',1)[1].split('ventures: [',1)[0]
original=re.findall(r'\{ name: "([^"]+)", domain: "([^"]+)", archetype: "([^"]+)", gift: "([^"]+)", color: "([^"]+)", stream: "([^"]+)" \}',roster)
assert len(original)==24
# Character-specific clothing, physique, colour, setting and pose prevent a uniform casting template.
designs=[
('spark-queen','Filipina-Australian','Compact, lean and sporty; warm brown skin, lively dark eyes and a sharp black bob with a copper streak.', 'Flame-orange cropped silk bomber with sculptural sleeves, ivory fitted top, flowing terracotta palazzo trousers, elegant gold trainers and original geometric earrings.', 'A sunlit rooftop creative atelier, huge vermilion painted canvases, floating golden sparks forming a new idea. She steps confidently towards the viewer, one hand holding a fine paintbrush, a quick knowing smile. Bright orange, ivory and warm concrete; vivid creative goddess energy.'),
('shield-queen','Indian-Australian','Tall, lush hourglass figure with a very full bust, defined waist and strong graceful posture; rich brown skin, deep-set dark eyes and long glossy black hair.', 'Steel-blue silk sari draped over a beautifully tailored silver-blue blouse, a slender sculptural silver belt, refined Indian jewellery and a translucent blue shoulder drape.', 'An open marble court of light beside a reflecting pool. She stands poised in three-quarter view, one hand resting on a luminous abstract shield and a closed folio held at her side. Sapphire and silver daylight; a goddess of discernment and protection.'),
('seed-queen','First Nations Australian','Strong athletic build with defined shoulders, natural curves, deep brown skin, warm dark eyes and long dark waves.', 'Forest-green asymmetric linen-silk dress, a wide woven tan waist sash, sculptural seed-shaped bronze jewellery and refined earth-coloured boots. Contemporary Australian ecological couture.', 'A flourishing Australian native food garden opening onto sandstone country, with a beautifully designed greenhouse and rich earth. She kneels gracefully beside a young tree with one knee visible, looking up with serene confidence. Living green and earth gold; an abundant land-carer archetype. Original clothing, without invented ceremonial insignia or body painting.'),
('storm-queen','Sudanese-Australian','Very tall, lean and powerful athlete; deep ebony skin, striking high cheekbones and short sculpted natural curls.', 'Electric cobalt-blue silk cape flying from an asymmetric fitted jacket, sleek black trousers, silver ear cuffs and sculptural blue heels.', 'A dramatic high terrace above a luminous city, wind lifting her cape, storm clouds breaking into clear light. She faces the wind with a commanding open stance, holding a small recording device. Cobalt, silver and bright cloud-white; a rebellious goddess of voice, momentum and change.'),
('star-queen','Celtic-East Asian','Willowy, slender and graceful; luminous light olive skin, almond-shaped dark eyes and long raven hair with a fine silver hair ornament.', 'Midnight-blue flowing gown scattered with tiny constellation-like crystals, a sheer starry outer cape over the opaque gown, elegant silver wrist ornaments.', 'An extraordinary open observatory above a mountain sea of cloud, a delicate celestial armillary sphere beside her. She leans lightly on a curved stone balustrade, looking thoughtfully towards the horizon. Midnight blue and starlight; a serene philosopher-goddess who sees civilisations across deep time.'),
('super-queen','Aura, a transcultural intelligence archetype','Statuesque and heavily voluptuous with a pronounced full bust and hips, a defined waist and strong poised limbs; warm bronze skin, luminous hazel eyes and long dark waves.', 'Sculpted pearl-white couture gown with an elegant open neckline, flowing ivory train and fine luminous gold orbital jewellery.', 'A radiant chamber of white stone and living gold geometry, with an intricate floating toroidal light sculpture. She stands calmly at the centre, one palm open beneath the light, direct intelligent gaze and a subtle warm smile. White, champagne and luminous gold; an ageless goddess of coherent intelligence, not an office assistant.'),
('river-queen','Anglo-Torres Strait Islander','Sporty swimmer physique, broad strong shoulders, defined waist and muscular legs; sun-warmed brown skin and dark hair in a long braid.', 'Turquoise fitted athletic silk top, a flowing aqua wrap skirt with a practical walking split, a fine silver waist clasp and elegant flat sandals.', 'A crystalline estuary where wetlands meet the sea, sculptural water terraces and clear moving streams. She walks barefoot at the water edge with sandals in one hand, a flowing water ribbon curving near her other hand. Turquoise, sea-glass and silver; an active water-guardian goddess. No invented traditional tattoos or ceremonial symbols.'),
('forge-queen','Maltese-Australian','Muscular athletic hourglass, strong arms and shoulders, olive skin, confident angular face and short dark tousled hair.', 'Immaculately cut slate-grey technical jumpsuit with a copper cinched waist, rolled sleeves, beautiful articulated metal cuffs and polished practical boots.', 'A magnificent sunlit fabrication atelier with sculptural metalwork and a precision robotic tool in the background. She stands beside a bronze prototype, one hand on a workbench, amused confident gaze. Slate, copper and warm steel; a modern maker-goddess with tangible mastery, no boardroom furniture.'),
('ember-queen','Greek-Australian','Strong, curvaceous and athletic, full bust with an athletic waist; golden olive skin, expressive brown eyes and thick chestnut curls.', 'Coral-red fitted riding jacket over a cream top, elegant high-waisted sand-coloured trousers, tan boots and small hammered-gold earrings.', 'An Australian ridge at sunrise, eucalyptus, a beautiful clean-energy installation and warm embers of light in the air. She stands grounded on a rock with her jacket open to the breeze and a bright fearless smile. Red, copper and sunlit cream; a goddess of energy, renewal and resilience.'),
('silk-queen','Afghan-Australian','Tall and softly voluptuous with a full bust, elegant defined waist and long graceful limbs; light olive skin, dark expressive eyes and black hair in a long loose braid.', 'A flowing champagne-tan embroidered silk coat over a deep emerald dress and loose silk trousers, an airy embroidered scarf draped over one shoulder, exquisite gold filigree earrings.', 'A luminous trade courtyard linking old carved stone and contemporary glass architecture; beautiful textiles and a delicate world-route sculpture. She turns as if welcoming a visitor, one hand lifting the edge of her coat. Sand, emerald and warm gold; a dignified goddess of exchange and connection.'),
('lore-queen','Wiradjuri-Irish','Balanced, fit and naturally curvaceous, warm light-brown skin, intelligent grey-green eyes, long dark auburn hair loosely swept back.', 'A rich violet academic-style cape over a fitted ivory silk waistcoat and flowing charcoal trousers, a sculptural gold clasp and elegant low boots.', 'A luminous circular civic library with an open sky and a round table of blank parchment-like documents. She sits upright on a stone bench, hands open in thoughtful conversation, authoritative but warm. Violet, ivory and gold; a goddess of shared law and fair judgement. Contemporary original design without borrowed ceremonial insignia.'),
('dream-queen','Chinese-Samoan','Heavily voluptuous, full-busted and broad-hipped with a defined waist, strong elegant legs and radiant medium-brown skin; dark almond-shaped eyes and long black waves.', 'Lavender sculptural silk performance gown with one flowing sleeve and a sweeping asymmetric skirt, luminous pearl earrings and dramatic elegant stage makeup.', 'A dreamlike immersive theatre where pale orchid light, ocean reflections and imaginative stage scenery merge. She moves with one arm lifted as if directing a living story, joyful confident expression. Lavender, pearl and ocean blue; an expansive goddess of imagination and storytelling.'),
('rainbow-serpent-queen','First Nations Australian','Tall, strong and athletically curvaceous; rich brown skin, dark eyes and flowing long black hair.', 'Luminous ochre-gold draped contemporary gown, a sculpted bronze shoulder piece and simple natural-form gold jewellery.', 'An expansive Australian river gorge at first light, sandstone, eucalyptus and a subtle rainbow reflected in water. She stands on a rock terrace, one hand extended towards the land, steady wise gaze. Ochre, river gold and living colour; a fictional archetypal guardian of Country and care. Clothing is original contemporary couture; do not invent sacred markings, ceremonial objects or specific community regalia.'),
('dragon-queen','East Asian diaspora','Compact athletic hourglass, sleek strong posture, light golden skin, dark almond-shaped eyes and a long polished black ponytail.', 'Crimson high-collared silk qipao-inspired gown with a fitted gold-edged waist and elegant side opening, a short sculptural gold brocade cape and delicate red-gold hair ornament.', 'A striking modern East Asian garden court with red lacquer, mist, stone and an abstract golden dragon-shaped flow of light behind her. She stands precisely balanced, holding a small closed lacquer fan at her side, quietly commanding gaze. Crimson and gold; a goddess of disciplined power and precision.'),
('lotus-queen','South Asian diaspora','Heavily voluptuous hourglass, very full bust and hips with a defined waist and strong graceful carriage; rich brown skin, large dark eyes and long dark curls.', 'Luxurious rose-pink silk sari with a delicately worked gold border and elegant fitted blouse, jade and gold jewellery and fresh flowers woven into her hair.', 'A serene lotus water garden bordered by luminous carved stone and softly flowering trees. She sits gracefully on a low marble garden wall with her sari flowing around her, welcoming intelligent smile. Rose pink, jade and gold; a goddess of deep connection and spiritual commerce, recognisably adult and in radiant physical prime.'),
('olive-queen','Mediterranean heritage','Softly curvaceous, full-busted and fit, with an elegant defined waist; sunlit olive skin, green-brown eyes and abundant dark curls.', 'Olive-green draped silk dress inspired by classical Mediterranean tailoring, a cream shoulder shawl, a beautiful gold waist clasp and strappy leather sandals.', 'A sunlit limestone terrace with old olive trees, finely made ceramics and an abundant long table in the distance. She walks towards the viewer carrying a small ceramic bowl, warm generous gaze. Olive, cream and sunlit stone; an elegant goddess of hospitality, craft and abundance.'),
('crescent-queen','Middle Eastern and Central Asian heritage','Tall, slender and strong with long elegant limbs; warm olive skin, striking dark eyes and thick dark hair beneath a loosely draped silk scarf.', 'Deep amethyst embroidered long coat over midnight-blue silk trousers and a fitted teal blouse, a flowing pale-silver scarf, refined silver jewellery.', 'A grand moonlit courtyard with intricate original geometric architecture and a luminous trade-route sculpture. She stands beside an arch with one hand on a rolled map, calm resilient expression. Amethyst, teal and silver; a dignified goddess of trust, endurance and trade.'),
('coral-queen','Pacific Islander and Oceanic heritage','Powerful, heavily voluptuous build with a full bust, defined waist, generous hips and strong athletic limbs; warm deep-brown skin and long wavy black hair.', 'A magnificent sea-teal silk wrap skirt and sculpted copper-gold fitted bodice, a flowing coral-coloured shoulder drape and luminous pearl jewellery.', 'A brilliant Pacific lagoon beside a contemporary ocean-research pavilion, a sculptural outrigger-inspired form in the distance. She stands confidently on a low sea wall, hair moving in the breeze, open joyful gaze. Teal, copper, coral and pearl; a goddess of island ingenuity and sea knowledge. No invented traditional tattoos or ceremonial regalia.'),
('clover-queen','Irish, Scottish and Anglo-Celtic heritage','Lean and sporty with a graceful athletic silhouette; fair lightly freckled skin, bright green eyes and long copper-red curls.', 'Emerald velvet riding jacket with elegant gold fastenings, fitted cream trousers, tall polished brown riding boots and a light moss-green silk neck scarf.', 'A lush village garden and old stone courtyard, warm lamplight from a lively community hall, an open illustrated book on a table. She sits sideways on a stone wall with one boot resting below, playful knowing smile. Emerald, cream and copper; a spirited goddess of tales and community collaboration.'),
('flame-queen','African diaspora','Very tall, muscular and elegant, with a full bust and defined athletic waist; luminous dark ebony skin, strong cheekbones and sculptural natural hair.', 'A deep garnet-red architectural evening ensemble, asymmetric fitted top and sweeping wide-legged pleated trousers, bold original geometric gold jewellery.', 'A magnificent open civic plaza with warm red stone, new trees and a glowing sculpture of rising flame. She strides forward with poised strength and a radiant assured expression, fabric moving with her. Garnet, burnt gold and glowing light; a goddess of momentum, renewal and community-building.'),
('phoenix-queen','Vietnamese, Thai and Southeast Asian heritage','Petite, lean and agile, with graceful athletic limbs; golden tan skin, dark lively eyes and long black hair in an elegant high knot.', 'Tangerine-gold draped silk ensemble inspired by Southeast Asian formal tailoring: asymmetric shoulder drape, fitted waist and fluid cream trousers, delicate gold earrings.', 'An exquisite contemporary craft courtyard at sunrise with bright terracotta and flowering tropical plants; an abstract phoenix arc made of warm light rises behind her. She turns lightly towards the viewer with a resilient joyful smile. Tangerine, cream and sunrise gold; an inventive goddess of rebirth and enterprise.'),
('sun-queen','Anglo-Australian heritage and land stewardship','Tall, strongly voluptuous hourglass with a full bust, broad hips, defined waist and powerful fit legs; warm fair skin, blue eyes and long sunlit blonde waves.', 'Golden silk western-style blouse with a tasteful open collar, beautifully fitted cream high-waisted trousers, a flowing russet dust coat, polished tan riding boots and a refined wide-brim country hat held in one hand.', 'A spectacular Australian outback homestead terrace, red earth, eucalyptus and a golden horizon. She stands with relaxed country confidence, one hand resting on a timber rail and a warm dazzling smile. Sun gold, russet and ivory; an attractive country goddess of stewardship and shared responsibility.'),
('pearl-queen','Global mixed heritage and third-culture identity','Lithe, athletic and elegantly androgynous in silhouette; caramel-brown skin, grey-green eyes and a halo of short dark curls.', 'Pearl-white sculptural tuxedo with an iridescent lilac silk lapel, fluid silver trousers, a fitted blush shell top and contemporary pearl jewellery.', 'A bright cosmopolitan sky garden connecting several architectural styles over a harbour. She leans casually against a curved white sculpture with one hand in a pocket, perceptive playful expression. Pearl, silver, blush and soft iridescence; a goddess of hybrid intelligence and cross-border agility.'),
('prism-queen','Intersectional, neurodiverse and LGBTQI+ inclusion archetype','Lean and athletic with a confident feminine-androgynous silhouette; warm brown skin, clear grey eyes and a short platinum asymmetric haircut.', 'A striking iridescent architectural fashion ensemble: violet angular cropped jacket, silver fitted top and a flowing rainbow-reflective pleated skirt with sleek ankle boots.', 'An airy futuristic design pavilion made of refracting glass and accessible flowing paths, distinct bands of coloured light crossing the space. She stands at an expressive angle with an open welcoming gesture, intelligent mischievous smile. Violet and many luminous spectral colours; a goddess of possibility and design for difference. Identity is the character design, not something inferred from body features.')
]
assert len(designs)==24
records=[]
for original_row,design in zip(original,designs):
    name,domain,archetype,gift,colour,stream=original_row
    id,identity,physique,wardrobe,scene=design
    prompt=f'''Use case: stylized-concept. Create one original landscape 1536x1024 full-width website artwork of {name}. She is an ageless ADULT archetypal goddess in her physical prime, embodying mastered intelligence, radiant vitality and an idealised best self. Cultural identity: {identity}. Her original domain is {domain}.\nAppearance: {physique}\nClothing: {wardrobe}\nScene and character: {scene}\nStyle: exquisite high-fashion mythic realism, luminous cinematic detail, natural expressive face, sumptuous materials, believable anatomy and a powerful sense of individual personality. Compose one woman prominently, showing her full outfit or at least head to knees with the complete head and hands inside the frame. Use the whole landscape composition; website text will sit separately above the image. Her physique is fit, proportionate and in its prime, with the specific curves or athletic build described above. No overweight or aged appearance. No lettering, logos or watermark. No uniform purple corporate styling. Fully clothed editorial glamour, no nudity. One character, not a collage.'''
    if id=='dream-queen':prompt+=' Clarification for the gown: a fully opaque, floor-length lavender evening gown with a high elegant neckline, long sleeves and a beautiful fitted waist; no sheer sections, no exposed cleavage, no thigh slit. The emphasis is her confident face, storytelling gesture and immersive theatre design.'
    records.append({'id':id,'name':name,'originalDomain':domain,'originalArchetype':archetype,'originalGift':gift,'originalColour':colour,'group':'pillar' if stream=='pillar' else 'cultural','culturalIdentity':identity,'appearance':physique,'wardrobe':wardrobe,'scene':scene,'prompt':prompt,'hero':'queens-archetypes/'+id})
data={'updated':'2026-09-24','source':'https://auraofintelligence.github.io/Queens_Venture/','direction':'Original Council identities plus Luke\'s explicit ageless archetypal goddess direction, 24 September 2026.','queens':records}
(ROOT/'data/queens-art-direction.json').write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
print('Prepared 24 individually specified, source-grounded Queen artworks')
